//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseMockOperation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseMockOperation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="defaultResponse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dispatchStyle" type="{http://eviware.com/soapui/config}MockOperationDispatchStyle" minOccurs="0"/>
 *         &lt;element name="dispatchPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseMockOperation", propOrder = {
    "defaultResponse",
    "dispatchStyle",
    "dispatchPath"
})
@XmlSeeAlso({
    MockOperation.class,
    RESTMockAction.class
})
public class BaseMockOperation
    extends ModelItem
{

    protected String defaultResponse;
    protected MockOperationDispatchStyle dispatchStyle;
    protected String dispatchPath;

    /**
     * Gets the value of the defaultResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultResponse() {
        return defaultResponse;
    }

    /**
     * Sets the value of the defaultResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultResponse(String value) {
        this.defaultResponse = value;
    }

    /**
     * Gets the value of the dispatchStyle property.
     * 
     * @return
     *     possible object is
     *     {@link MockOperationDispatchStyle }
     *     
     */
    public MockOperationDispatchStyle getDispatchStyle() {
        return dispatchStyle;
    }

    /**
     * Sets the value of the dispatchStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MockOperationDispatchStyle }
     *     
     */
    public void setDispatchStyle(MockOperationDispatchStyle value) {
        this.dispatchStyle = value;
    }

    /**
     * Gets the value of the dispatchPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatchPath() {
        return dispatchPath;
    }

    /**
     * Sets the value of the dispatchPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatchPath(String value) {
        this.dispatchPath = value;
    }

}
