//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseMockService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseMockService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="startScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="stopScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *         &lt;element name="onRequestScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="afterRequestScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bindToHostOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="docroot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="faultMockOperation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dispatchResponseMessages" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseMockService", propOrder = {
    "startScript",
    "stopScript",
    "properties",
    "onRequestScript",
    "afterRequestScript"
})
@XmlSeeAlso({
    MockService.class,
    RESTMockService.class
})
public class BaseMockService
    extends ModelItem
{

    protected Script startScript;
    protected Script stopScript;
    protected PropertiesType properties;
    protected Script onRequestScript;
    protected Script afterRequestScript;
    @XmlAttribute(name = "port")
    protected Integer port;
    @XmlAttribute(name = "host")
    protected String host;
    @XmlAttribute(name = "bindToHostOnly")
    protected Boolean bindToHostOnly;
    @XmlAttribute(name = "path")
    protected String path;
    @XmlAttribute(name = "docroot")
    protected String docroot;
    @XmlAttribute(name = "faultMockOperation")
    protected String faultMockOperation;
    @XmlAttribute(name = "dispatchResponseMessages")
    protected Boolean dispatchResponseMessages;

    /**
     * Gets the value of the startScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getStartScript() {
        return startScript;
    }

    /**
     * Sets the value of the startScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setStartScript(Script value) {
        this.startScript = value;
    }

    /**
     * Gets the value of the stopScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getStopScript() {
        return stopScript;
    }

    /**
     * Sets the value of the stopScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setStopScript(Script value) {
        this.stopScript = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the onRequestScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getOnRequestScript() {
        return onRequestScript;
    }

    /**
     * Sets the value of the onRequestScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setOnRequestScript(Script value) {
        this.onRequestScript = value;
    }

    /**
     * Gets the value of the afterRequestScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getAfterRequestScript() {
        return afterRequestScript;
    }

    /**
     * Sets the value of the afterRequestScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setAfterRequestScript(Script value) {
        this.afterRequestScript = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPort(Integer value) {
        this.port = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the bindToHostOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBindToHostOnly() {
        return bindToHostOnly;
    }

    /**
     * Sets the value of the bindToHostOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBindToHostOnly(Boolean value) {
        this.bindToHostOnly = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the docroot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocroot() {
        return docroot;
    }

    /**
     * Sets the value of the docroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocroot(String value) {
        this.docroot = value;
    }

    /**
     * Gets the value of the faultMockOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultMockOperation() {
        return faultMockOperation;
    }

    /**
     * Sets the value of the faultMockOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultMockOperation(String value) {
        this.faultMockOperation = value;
    }

    /**
     * Gets the value of the dispatchResponseMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDispatchResponseMessages() {
        return dispatchResponseMessages;
    }

    /**
     * Sets the value of the dispatchResponseMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDispatchResponseMessages(Boolean value) {
        this.dispatchResponseMessages = value;
    }

}
