//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataSourceStep complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataSourceStep">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataSource" type="{http://eviware.com/soapui/config}DataSource"/>
 *         &lt;element name="shared" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="restartShared" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="preload" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="property" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="startRow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endRow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="failOnEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="gotoLoopOnEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="trimValues" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="entitizeValues" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="restartOnRun" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="expandProperties" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSourceStep", propOrder = {
    "dataSource",
    "shared",
    "restartShared",
    "preload",
    "property",
    "startRow",
    "endRow",
    "failOnEmpty",
    "gotoLoopOnEmpty",
    "trimValues",
    "entitizeValues",
    "restartOnRun",
    "expandProperties"
})
public class DataSourceStep {

    @XmlElement(required = true)
    protected DataSource dataSource;
    protected boolean shared;
    protected boolean restartShared;
    protected boolean preload;
    protected List<String> property;
    @XmlElement(required = true)
    protected String startRow;
    @XmlElement(required = true)
    protected String endRow;
    protected Boolean failOnEmpty;
    protected boolean gotoLoopOnEmpty;
    protected boolean trimValues;
    protected boolean entitizeValues;
    protected boolean restartOnRun;
    protected boolean expandProperties;

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link DataSource }
     *     
     */
    public DataSource getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSource }
     *     
     */
    public void setDataSource(DataSource value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the shared property.
     * 
     */
    public boolean isShared() {
        return shared;
    }

    /**
     * Sets the value of the shared property.
     * 
     */
    public void setShared(boolean value) {
        this.shared = value;
    }

    /**
     * Gets the value of the restartShared property.
     * 
     */
    public boolean isRestartShared() {
        return restartShared;
    }

    /**
     * Sets the value of the restartShared property.
     * 
     */
    public void setRestartShared(boolean value) {
        this.restartShared = value;
    }

    /**
     * Gets the value of the preload property.
     * 
     */
    public boolean isPreload() {
        return preload;
    }

    /**
     * Sets the value of the preload property.
     * 
     */
    public void setPreload(boolean value) {
        this.preload = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProperty() {
        if (property == null) {
            property = new ArrayList<String>();
        }
        return this.property;
    }

    /**
     * Gets the value of the startRow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartRow() {
        return startRow;
    }

    /**
     * Sets the value of the startRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartRow(String value) {
        this.startRow = value;
    }

    /**
     * Gets the value of the endRow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndRow() {
        return endRow;
    }

    /**
     * Sets the value of the endRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndRow(String value) {
        this.endRow = value;
    }

    /**
     * Gets the value of the failOnEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailOnEmpty() {
        return failOnEmpty;
    }

    /**
     * Sets the value of the failOnEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailOnEmpty(Boolean value) {
        this.failOnEmpty = value;
    }

    /**
     * Gets the value of the gotoLoopOnEmpty property.
     * 
     */
    public boolean isGotoLoopOnEmpty() {
        return gotoLoopOnEmpty;
    }

    /**
     * Sets the value of the gotoLoopOnEmpty property.
     * 
     */
    public void setGotoLoopOnEmpty(boolean value) {
        this.gotoLoopOnEmpty = value;
    }

    /**
     * Gets the value of the trimValues property.
     * 
     */
    public boolean isTrimValues() {
        return trimValues;
    }

    /**
     * Sets the value of the trimValues property.
     * 
     */
    public void setTrimValues(boolean value) {
        this.trimValues = value;
    }

    /**
     * Gets the value of the entitizeValues property.
     * 
     */
    public boolean isEntitizeValues() {
        return entitizeValues;
    }

    /**
     * Sets the value of the entitizeValues property.
     * 
     */
    public void setEntitizeValues(boolean value) {
        this.entitizeValues = value;
    }

    /**
     * Gets the value of the restartOnRun property.
     * 
     */
    public boolean isRestartOnRun() {
        return restartOnRun;
    }

    /**
     * Sets the value of the restartOnRun property.
     * 
     */
    public void setRestartOnRun(boolean value) {
        this.restartOnRun = value;
    }

    /**
     * Gets the value of the expandProperties property.
     * 
     */
    public boolean isExpandProperties() {
        return expandProperties;
    }

    /**
     * Sets the value of the expandProperties property.
     * 
     */
    public void setExpandProperties(boolean value) {
        this.expandProperties = value;
    }

}
