//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DefinitionCache complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefinitionCache">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="part" type="{http://eviware.com/soapui/config}DefintionPart"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rootPart" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cacheTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="type" type="{http://eviware.com/soapui/config}DefinitionCacheType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefinitionCache", propOrder = {
    "part"
})
public class DefinitionCache {

    @XmlElement(required = true)
    protected List<DefintionPart> part;
    @XmlAttribute(name = "rootPart")
    protected String rootPart;
    @XmlAttribute(name = "cacheTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cacheTime;
    @XmlAttribute(name = "type")
    protected DefinitionCacheType type;

    /**
     * Gets the value of the part property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the part property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefintionPart }
     * 
     * 
     */
    public List<DefintionPart> getPart() {
        if (part == null) {
            part = new ArrayList<DefintionPart>();
        }
        return this.part;
    }

    /**
     * Gets the value of the rootPart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootPart() {
        return rootPart;
    }

    /**
     * Sets the value of the rootPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootPart(String value) {
        this.rootPart = value;
    }

    /**
     * Gets the value of the cacheTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCacheTime() {
        return cacheTime;
    }

    /**
     * Sets the value of the cacheTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCacheTime(XMLGregorianCalendar value) {
        this.cacheTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DefinitionCacheType }
     *     
     */
    public DefinitionCacheType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefinitionCacheType }
     *     
     */
    public void setType(DefinitionCacheType value) {
        this.type = value;
    }

}
