//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroovySecurityScan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroovySecurityScan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="executeScript" type="{http://eviware.com/soapui/config}Script"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroovySecurityScan", propOrder = {
    "executeScript"
})
public class GroovySecurityScan {

    @XmlElement(required = true)
    protected Script executeScript;

    /**
     * Gets the value of the executeScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getExecuteScript() {
        return executeScript;
    }

    /**
     * Sets the value of the executeScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setExecuteScript(Script value) {
        this.executeScript = value;
    }

}
