//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Interface complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Interface">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="definitionCache" type="{http://eviware.com/soapui/config}DefinitionCache" minOccurs="0"/>
 *         &lt;element name="endpoints" type="{http://eviware.com/soapui/config}Endpoints"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Interface", propOrder = {
    "definitionCache",
    "endpoints"
})
@XmlSeeAlso({
    RestService.class,
    WsdlInterface.class
})
public class Interface
    extends ModelItem
{

    protected DefinitionCache definitionCache;
    @XmlElement(required = true)
    protected Endpoints endpoints;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the definitionCache property.
     * 
     * @return
     *     possible object is
     *     {@link DefinitionCache }
     *     
     */
    public DefinitionCache getDefinitionCache() {
        return definitionCache;
    }

    /**
     * Sets the value of the definitionCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefinitionCache }
     *     
     */
    public void setDefinitionCache(DefinitionCache value) {
        this.definitionCache = value;
    }

    /**
     * Gets the value of the endpoints property.
     * 
     * @return
     *     possible object is
     *     {@link Endpoints }
     *     
     */
    public Endpoints getEndpoints() {
        return endpoints;
    }

    /**
     * Sets the value of the endpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endpoints }
     *     
     */
    public void setEndpoints(Endpoints value) {
        this.endpoints = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
