//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyIdentifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KeyIdentifierType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ISSUER_SERIAL"/>
 *     &lt;enumeration value="BST_DIRECT_REFERENCE"/>
 *     &lt;enumeration value="X509_KEY_IDENTIFIER"/>
 *     &lt;enumeration value="SKI_KEY_IDENTIFIER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KeyIdentifierType")
@XmlEnum
public enum KeyIdentifierType {

    ISSUER_SERIAL("ISSUER_SERIAL"),
    BST_DIRECT_REFERENCE("BST_DIRECT_REFERENCE"),
    @XmlEnumValue("X509_KEY_IDENTIFIER")
    X_509_KEY_IDENTIFIER("X509_KEY_IDENTIFIER"),
    SKI_KEY_IDENTIFIER("SKI_KEY_IDENTIFIER");
    private final String value;

    KeyIdentifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KeyIdentifierType fromValue(String v) {
        for (KeyIdentifierType c: KeyIdentifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
