//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MalformedXml complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MalformedXml">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="insertNewElement" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="newElementValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leaveTagOpen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="changeTagName" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="attributeMutation" type="{http://eviware.com/soapui/config}MalformedXmlAttribute"/>
 *         &lt;element name="insertInvalidCharacter" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MalformedXml", propOrder = {
    "insertNewElement",
    "newElementValue",
    "leaveTagOpen",
    "changeTagName",
    "attributeMutation",
    "insertInvalidCharacter"
})
public class MalformedXml {

    protected boolean insertNewElement;
    @XmlElement(required = true)
    protected String newElementValue;
    protected boolean leaveTagOpen;
    protected boolean changeTagName;
    @XmlElement(required = true)
    protected MalformedXmlAttribute attributeMutation;
    protected boolean insertInvalidCharacter;

    /**
     * Gets the value of the insertNewElement property.
     * 
     */
    public boolean isInsertNewElement() {
        return insertNewElement;
    }

    /**
     * Sets the value of the insertNewElement property.
     * 
     */
    public void setInsertNewElement(boolean value) {
        this.insertNewElement = value;
    }

    /**
     * Gets the value of the newElementValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewElementValue() {
        return newElementValue;
    }

    /**
     * Sets the value of the newElementValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewElementValue(String value) {
        this.newElementValue = value;
    }

    /**
     * Gets the value of the leaveTagOpen property.
     * 
     */
    public boolean isLeaveTagOpen() {
        return leaveTagOpen;
    }

    /**
     * Sets the value of the leaveTagOpen property.
     * 
     */
    public void setLeaveTagOpen(boolean value) {
        this.leaveTagOpen = value;
    }

    /**
     * Gets the value of the changeTagName property.
     * 
     */
    public boolean isChangeTagName() {
        return changeTagName;
    }

    /**
     * Sets the value of the changeTagName property.
     * 
     */
    public void setChangeTagName(boolean value) {
        this.changeTagName = value;
    }

    /**
     * Gets the value of the attributeMutation property.
     * 
     * @return
     *     possible object is
     *     {@link MalformedXmlAttribute }
     *     
     */
    public MalformedXmlAttribute getAttributeMutation() {
        return attributeMutation;
    }

    /**
     * Sets the value of the attributeMutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MalformedXmlAttribute }
     *     
     */
    public void setAttributeMutation(MalformedXmlAttribute value) {
        this.attributeMutation = value;
    }

    /**
     * Gets the value of the insertInvalidCharacter property.
     * 
     */
    public boolean isInsertInvalidCharacter() {
        return insertInvalidCharacter;
    }

    /**
     * Sets the value of the insertInvalidCharacter property.
     * 
     */
    public void setInsertInvalidCharacter(boolean value) {
        this.insertInvalidCharacter = value;
    }

}
