//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MockService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MockService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}BaseMockService">
 *       &lt;sequence>
 *         &lt;element name="mockOperation" type="{http://eviware.com/soapui/config}MockOperation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="incomingWss" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outgoingWss" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MockService", propOrder = {
    "mockOperation"
})
public class MockService
    extends BaseMockService
{

    protected List<MockOperation> mockOperation;
    @XmlAttribute(name = "incomingWss")
    protected String incomingWss;
    @XmlAttribute(name = "outgoingWss")
    protected String outgoingWss;

    /**
     * Gets the value of the mockOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mockOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMockOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MockOperation }
     * 
     * 
     */
    public List<MockOperation> getMockOperation() {
        if (mockOperation == null) {
            mockOperation = new ArrayList<MockOperation>();
        }
        return this.mockOperation;
    }

    /**
     * Gets the value of the incomingWss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomingWss() {
        return incomingWss;
    }

    /**
     * Sets the value of the incomingWss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomingWss(String value) {
        this.incomingWss = value;
    }

    /**
     * Gets the value of the outgoingWss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutgoingWss() {
        return outgoingWss;
    }

    /**
     * Sets the value of the outgoingWss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutgoingWss(String value) {
        this.outgoingWss = value;
    }

}
