//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MockResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MockResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}BaseMockResponse">
 *       &lt;sequence>
 *         &lt;element name="wsaConfig" type="{http://eviware.com/soapui/config}WsaConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="outgoingWss" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="useWsAddressing" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MockResponse", propOrder = {
    "wsaConfig"
})
public class MockResponse
    extends BaseMockResponse
{

    protected WsaConfig wsaConfig;
    @XmlAttribute(name = "outgoingWss")
    protected String outgoingWss;
    @XmlAttribute(name = "useWsAddressing")
    protected Boolean useWsAddressing;

    /**
     * Gets the value of the wsaConfig property.
     * 
     * @return
     *     possible object is
     *     {@link WsaConfig }
     *     
     */
    public WsaConfig getWsaConfig() {
        return wsaConfig;
    }

    /**
     * Sets the value of the wsaConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsaConfig }
     *     
     */
    public void setWsaConfig(WsaConfig value) {
        this.wsaConfig = value;
    }

    /**
     * Gets the value of the outgoingWss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutgoingWss() {
        return outgoingWss;
    }

    /**
     * Sets the value of the outgoingWss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutgoingWss(String value) {
        this.outgoingWss = value;
    }

    /**
     * Gets the value of the useWsAddressing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseWsAddressing() {
        return useWsAddressing;
    }

    /**
     * Sets the value of the useWsAddressing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseWsAddressing(Boolean value) {
        this.useWsAddressing = value;
    }

}
