//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MockOperation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MockOperation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}BaseMockOperation">
 *       &lt;sequence>
 *         &lt;element name="response" type="{http://eviware.com/soapui/config}MockResponse" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dispatchConfig" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="interface" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="faultMockOperation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MockOperation", propOrder = {
    "response",
    "dispatchConfig"
})
public class MockOperation
    extends BaseMockOperation
{

    protected List<MockResponse> response;
    protected Object dispatchConfig;
    @XmlAttribute(name = "interface")
    protected String _interface;
    @XmlAttribute(name = "operation")
    protected String operation;
    @XmlAttribute(name = "faultMockOperation")
    protected String faultMockOperation;

    /**
     * Gets the value of the response property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the response property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MockResponse }
     * 
     * 
     */
    public List<MockResponse> getResponse() {
        if (response == null) {
            response = new ArrayList<MockResponse>();
        }
        return this.response;
    }

    /**
     * Gets the value of the dispatchConfig property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDispatchConfig() {
        return dispatchConfig;
    }

    /**
     * Sets the value of the dispatchConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDispatchConfig(Object value) {
        this.dispatchConfig = value;
    }

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterface(String value) {
        this._interface = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the faultMockOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultMockOperation() {
        return faultMockOperation;
    }

    /**
     * Sets the value of the faultMockOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultMockOperation(String value) {
        this.faultMockOperation = value;
    }

}
