//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OldRestRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OldRestRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}AbstractRequest">
 *       &lt;sequence>
 *         &lt;element name="parameters" type="{http://eviware.com/soapui/config}RestParameters"/>
 *         &lt;element name="representation" type="{http://eviware.com/soapui/config}RestResourceRepresentation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wadlId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fullPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mediaType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postQueryString" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="accept" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OldRestRequest", propOrder = {
    "parameters",
    "representation"
})
public class OldRestRequest
    extends AbstractRequest
{

    @XmlElement(required = true)
    protected RestParameters parameters;
    protected List<RestResourceRepresentation> representation;
    @XmlAttribute(name = "method")
    protected String method;
    @XmlAttribute(name = "wadlId")
    protected String wadlId;
    @XmlAttribute(name = "fullPath")
    protected String fullPath;
    @XmlAttribute(name = "mediaType")
    protected String mediaType;
    @XmlAttribute(name = "postQueryString")
    protected Boolean postQueryString;
    @XmlAttribute(name = "accept")
    protected String accept;

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link RestParameters }
     *     
     */
    public RestParameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestParameters }
     *     
     */
    public void setParameters(RestParameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the representation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the representation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepresentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestResourceRepresentation }
     * 
     * 
     */
    public List<RestResourceRepresentation> getRepresentation() {
        if (representation == null) {
            representation = new ArrayList<RestResourceRepresentation>();
        }
        return this.representation;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the wadlId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWadlId() {
        return wadlId;
    }

    /**
     * Sets the value of the wadlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWadlId(String value) {
        this.wadlId = value;
    }

    /**
     * Gets the value of the fullPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * Sets the value of the fullPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullPath(String value) {
        this.fullPath = value;
    }

    /**
     * Gets the value of the mediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }

    /**
     * Gets the value of the postQueryString property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPostQueryString() {
        return postQueryString;
    }

    /**
     * Sets the value of the postQueryString property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPostQueryString(Boolean value) {
        this.postQueryString = value;
    }

    /**
     * Gets the value of the accept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccept() {
        return accept;
    }

    /**
     * Sets the value of the accept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccept(String value) {
        this.accept = value;
    }

}
