//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Operation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="call" type="{http://eviware.com/soapui/config}WsdlRequest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requestParts" type="{http://eviware.com/soapui/config}Parts" minOccurs="0"/>
 *         &lt;element name="responseParts" type="{http://eviware.com/soapui/config}Parts" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bindingOperationName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="style" type="{http://eviware.com/soapui/config}OperationStyles" />
 *       &lt;attribute name="type" type="{http://eviware.com/soapui/config}OperationTypes" />
 *       &lt;attribute name="inputName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outputName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isOneWay" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="sendsAttachments" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="receivesAttachments" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="anonymous" type="{http://eviware.com/soapui/config}AnonymousType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Operation", propOrder = {
    "call",
    "requestParts",
    "responseParts"
})
public class Operation
    extends ModelItem
{

    protected List<WsdlRequest> call;
    protected Parts requestParts;
    protected Parts responseParts;
    @XmlAttribute(name = "action")
    protected String action;
    @XmlAttribute(name = "bindingOperationName")
    protected String bindingOperationName;
    @XmlAttribute(name = "style")
    protected OperationStyles style;
    @XmlAttribute(name = "type")
    protected OperationTypes type;
    @XmlAttribute(name = "inputName")
    protected String inputName;
    @XmlAttribute(name = "outputName")
    protected String outputName;
    @XmlAttribute(name = "isOneWay")
    protected Boolean isOneWay;
    @XmlAttribute(name = "sendsAttachments")
    protected Boolean sendsAttachments;
    @XmlAttribute(name = "receivesAttachments")
    protected Boolean receivesAttachments;
    @XmlAttribute(name = "anonymous")
    protected AnonymousType anonymous;

    /**
     * Gets the value of the call property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the call property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsdlRequest }
     * 
     * 
     */
    public List<WsdlRequest> getCall() {
        if (call == null) {
            call = new ArrayList<WsdlRequest>();
        }
        return this.call;
    }

    /**
     * Gets the value of the requestParts property.
     * 
     * @return
     *     possible object is
     *     {@link Parts }
     *     
     */
    public Parts getRequestParts() {
        return requestParts;
    }

    /**
     * Sets the value of the requestParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parts }
     *     
     */
    public void setRequestParts(Parts value) {
        this.requestParts = value;
    }

    /**
     * Gets the value of the responseParts property.
     * 
     * @return
     *     possible object is
     *     {@link Parts }
     *     
     */
    public Parts getResponseParts() {
        return responseParts;
    }

    /**
     * Sets the value of the responseParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parts }
     *     
     */
    public void setResponseParts(Parts value) {
        this.responseParts = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the bindingOperationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindingOperationName() {
        return bindingOperationName;
    }

    /**
     * Sets the value of the bindingOperationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindingOperationName(String value) {
        this.bindingOperationName = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link OperationStyles }
     *     
     */
    public OperationStyles getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationStyles }
     *     
     */
    public void setStyle(OperationStyles value) {
        this.style = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link OperationTypes }
     *     
     */
    public OperationTypes getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationTypes }
     *     
     */
    public void setType(OperationTypes value) {
        this.type = value;
    }

    /**
     * Gets the value of the inputName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * Sets the value of the inputName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputName(String value) {
        this.inputName = value;
    }

    /**
     * Gets the value of the outputName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputName() {
        return outputName;
    }

    /**
     * Sets the value of the outputName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputName(String value) {
        this.outputName = value;
    }

    /**
     * Gets the value of the isOneWay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsOneWay() {
        if (isOneWay == null) {
            return false;
        } else {
            return isOneWay;
        }
    }

    /**
     * Sets the value of the isOneWay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOneWay(Boolean value) {
        this.isOneWay = value;
    }

    /**
     * Gets the value of the sendsAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSendsAttachments() {
        return sendsAttachments;
    }

    /**
     * Sets the value of the sendsAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSendsAttachments(Boolean value) {
        this.sendsAttachments = value;
    }

    /**
     * Gets the value of the receivesAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReceivesAttachments() {
        return receivesAttachments;
    }

    /**
     * Sets the value of the receivesAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReceivesAttachments(Boolean value) {
        this.receivesAttachments = value;
    }

    /**
     * Gets the value of the anonymous property.
     * 
     * @return
     *     possible object is
     *     {@link AnonymousType }
     *     
     */
    public AnonymousType getAnonymous() {
        return anonymous;
    }

    /**
     * Sets the value of the anonymous property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnonymousType }
     *     
     */
    public void setAnonymous(AnonymousType value) {
        this.anonymous = value;
    }

}
