//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutgoingWss complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutgoingWss">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="entry" type="{http://eviware.com/soapui/config}WSSEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="enableSignatureConfirmation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="precisionInMilliSeconds" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="timeStampScript" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="wsiBspCompliant" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="actor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mustUnderstand" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutgoingWss", propOrder = {
    "name",
    "username",
    "password",
    "entry"
})
public class OutgoingWss {

    @XmlElement(required = true)
    protected String name;
    protected String username;
    protected String password;
    protected List<WSSEntry> entry;
    @XmlAttribute(name = "enableSignatureConfirmation")
    protected Boolean enableSignatureConfirmation;
    @XmlAttribute(name = "precisionInMilliSeconds")
    protected Boolean precisionInMilliSeconds;
    @XmlAttribute(name = "timeStampScript")
    protected Boolean timeStampScript;
    @XmlAttribute(name = "wsiBspCompliant")
    protected Boolean wsiBspCompliant;
    @XmlAttribute(name = "actor")
    protected String actor;
    @XmlAttribute(name = "mustUnderstand")
    protected Boolean mustUnderstand;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WSSEntry }
     * 
     * 
     */
    public List<WSSEntry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<WSSEntry>();
        }
        return this.entry;
    }

    /**
     * Gets the value of the enableSignatureConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableSignatureConfirmation() {
        return enableSignatureConfirmation;
    }

    /**
     * Sets the value of the enableSignatureConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableSignatureConfirmation(Boolean value) {
        this.enableSignatureConfirmation = value;
    }

    /**
     * Gets the value of the precisionInMilliSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrecisionInMilliSeconds() {
        return precisionInMilliSeconds;
    }

    /**
     * Sets the value of the precisionInMilliSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrecisionInMilliSeconds(Boolean value) {
        this.precisionInMilliSeconds = value;
    }

    /**
     * Gets the value of the timeStampScript property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimeStampScript() {
        return timeStampScript;
    }

    /**
     * Sets the value of the timeStampScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeStampScript(Boolean value) {
        this.timeStampScript = value;
    }

    /**
     * Gets the value of the wsiBspCompliant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWsiBspCompliant() {
        return wsiBspCompliant;
    }

    /**
     * Sets the value of the wsiBspCompliant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWsiBspCompliant(Boolean value) {
        this.wsiBspCompliant = value;
    }

    /**
     * Gets the value of the actor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActor() {
        return actor;
    }

    /**
     * Sets the value of the actor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActor(String value) {
        this.actor = value;
    }

    /**
     * Gets the value of the mustUnderstand property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMustUnderstand() {
        return mustUnderstand;
    }

    /**
     * Sets the value of the mustUnderstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMustUnderstand(Boolean value) {
        this.mustUnderstand = value;
    }

}
