//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RESTMockService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RESTMockService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}BaseMockService">
 *       &lt;sequence>
 *         &lt;element name="restMockAction" type="{http://eviware.com/soapui/config}RESTMockAction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RESTMockService", propOrder = {
    "restMockAction"
})
public class RESTMockService
    extends BaseMockService
{

    protected List<RESTMockAction> restMockAction;

    /**
     * Gets the value of the restMockAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restMockAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestMockAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RESTMockAction }
     * 
     * 
     */
    public List<RESTMockAction> getRestMockAction() {
        if (restMockAction == null) {
            restMockAction = new ArrayList<RESTMockAction>();
        }
        return this.restMockAction;
    }

}
