//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RunTestSuiteStep complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RunTestSuiteStep">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targetTestSuite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="properties" type="{http://eviware.com/soapui/config}PropertiesType"/>
 *         &lt;element name="returnProperties" type="{http://eviware.com/soapui/config}StringList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunTestSuiteStep", propOrder = {
    "targetTestSuite",
    "properties",
    "returnProperties"
})
public class RunTestSuiteStep {

    @XmlElement(required = true)
    protected String targetTestSuite;
    @XmlElement(required = true)
    protected PropertiesType properties;
    @XmlElement(required = true)
    protected StringList returnProperties;

    /**
     * Gets the value of the targetTestSuite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetTestSuite() {
        return targetTestSuite;
    }

    /**
     * Sets the value of the targetTestSuite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetTestSuite(String value) {
        this.targetTestSuite = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the returnProperties property.
     * 
     * @return
     *     possible object is
     *     {@link StringList }
     *     
     */
    public StringList getReturnProperties() {
        return returnProperties;
    }

    /**
     * Sets the value of the returnProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringList }
     *     
     */
    public void setReturnProperties(StringList value) {
        this.returnProperties = value;
    }

}
