//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityTest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="setupScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="tearDownScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="testStepSecurityTest" type="{http://eviware.com/soapui/config}TestStepSecurityTest" maxOccurs="unbounded"/>
 *         &lt;element name="properties" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *         &lt;element name="reportScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="reportParameters" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="failOnError" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="failSecurityTestOnCheckErrors" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="failSecurityTestOnScanErrors" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="skipDataSourceLoops" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityTest", propOrder = {
    "setupScript",
    "tearDownScript",
    "testStepSecurityTest",
    "properties",
    "reportScript",
    "reportParameters"
})
public class SecurityTest
    extends ModelItem
{

    protected Script setupScript;
    protected Script tearDownScript;
    @XmlElement(required = true)
    protected List<TestStepSecurityTest> testStepSecurityTest;
    protected PropertiesType properties;
    protected Script reportScript;
    protected PropertiesType reportParameters;
    @XmlAttribute(name = "failOnError")
    protected Boolean failOnError;
    @XmlAttribute(name = "failSecurityTestOnCheckErrors")
    protected Boolean failSecurityTestOnCheckErrors;
    @XmlAttribute(name = "failSecurityTestOnScanErrors")
    protected Boolean failSecurityTestOnScanErrors;
    @XmlAttribute(name = "skipDataSourceLoops")
    protected Boolean skipDataSourceLoops;

    /**
     * Gets the value of the setupScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getSetupScript() {
        return setupScript;
    }

    /**
     * Sets the value of the setupScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setSetupScript(Script value) {
        this.setupScript = value;
    }

    /**
     * Gets the value of the tearDownScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getTearDownScript() {
        return tearDownScript;
    }

    /**
     * Sets the value of the tearDownScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setTearDownScript(Script value) {
        this.tearDownScript = value;
    }

    /**
     * Gets the value of the testStepSecurityTest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testStepSecurityTest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestStepSecurityTest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestStepSecurityTest }
     * 
     * 
     */
    public List<TestStepSecurityTest> getTestStepSecurityTest() {
        if (testStepSecurityTest == null) {
            testStepSecurityTest = new ArrayList<TestStepSecurityTest>();
        }
        return this.testStepSecurityTest;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the reportScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getReportScript() {
        return reportScript;
    }

    /**
     * Sets the value of the reportScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setReportScript(Script value) {
        this.reportScript = value;
    }

    /**
     * Gets the value of the reportParameters property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getReportParameters() {
        return reportParameters;
    }

    /**
     * Sets the value of the reportParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setReportParameters(PropertiesType value) {
        this.reportParameters = value;
    }

    /**
     * Gets the value of the failOnError property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailOnError() {
        return failOnError;
    }

    /**
     * Sets the value of the failOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailOnError(Boolean value) {
        this.failOnError = value;
    }

    /**
     * Gets the value of the failSecurityTestOnCheckErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailSecurityTestOnCheckErrors() {
        return failSecurityTestOnCheckErrors;
    }

    /**
     * Sets the value of the failSecurityTestOnCheckErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailSecurityTestOnCheckErrors(Boolean value) {
        this.failSecurityTestOnCheckErrors = value;
    }

    /**
     * Gets the value of the failSecurityTestOnScanErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailSecurityTestOnScanErrors() {
        return failSecurityTestOnScanErrors;
    }

    /**
     * Sets the value of the failSecurityTestOnScanErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailSecurityTestOnScanErrors(Boolean value) {
        this.failSecurityTestOnScanErrors = value;
    }

    /**
     * Gets the value of the skipDataSourceLoops property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSkipDataSourceLoops() {
        return skipDataSourceLoops;
    }

    /**
     * Sets the value of the skipDataSourceLoops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSkipDataSourceLoops(Boolean value) {
        this.skipDataSourceLoops = value;
    }

}
