//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestStepSecurityTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestStepSecurityTest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testStepId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testStepSecurityCheck" type="{http://eviware.com/soapui/config}SecurityCheck" maxOccurs="unbounded"/>
 *         &lt;element name="testStepSecurityScan" type="{http://eviware.com/soapui/config}SecurityScan" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestStepSecurityTest", propOrder = {
    "testStepId",
    "testStepSecurityCheck",
    "testStepSecurityScan"
})
public class TestStepSecurityTest {

    @XmlElement(required = true)
    protected String testStepId;
    @XmlElement(required = true)
    protected List<SecurityCheck> testStepSecurityCheck;
    @XmlElement(required = true)
    protected List<SecurityScan> testStepSecurityScan;

    /**
     * Gets the value of the testStepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestStepId() {
        return testStepId;
    }

    /**
     * Sets the value of the testStepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestStepId(String value) {
        this.testStepId = value;
    }

    /**
     * Gets the value of the testStepSecurityCheck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testStepSecurityCheck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestStepSecurityCheck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityCheck }
     * 
     * 
     */
    public List<SecurityCheck> getTestStepSecurityCheck() {
        if (testStepSecurityCheck == null) {
            testStepSecurityCheck = new ArrayList<SecurityCheck>();
        }
        return this.testStepSecurityCheck;
    }

    /**
     * Gets the value of the testStepSecurityScan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testStepSecurityScan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestStepSecurityScan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityScan }
     * 
     * 
     */
    public List<SecurityScan> getTestStepSecurityScan() {
        if (testStepSecurityScan == null) {
            testStepSecurityScan = new ArrayList<SecurityScan>();
        }
        return this.testStepSecurityScan;
    }

}
