//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestCase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestCase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="testStep" type="{http://eviware.com/soapui/config}TestStep" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loadTest" type="{http://eviware.com/soapui/config}LoadTest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="setupScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="tearDownScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *         &lt;element name="requirements" type="{http://eviware.com/soapui/config}RequirementsType" minOccurs="0"/>
 *         &lt;element name="reportTemplates" type="{http://eviware.com/soapui/config}ReportTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reportScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="reportParameters" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *         &lt;element name="securityTest" type="{http://eviware.com/soapui/config}SecurityTest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="breakPoints" type="{http://eviware.com/soapui/config}BreakPoint" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keepSession" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="failOnError" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="failTestCaseOnErrors" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="discardOkResults" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="searchProperties" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="maxResults" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="wsrmEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="wsrmVersion" type="{http://eviware.com/soapui/config}WsrmVersionType" />
 *       &lt;attribute name="wsrmAckTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wsrmExpires" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="amfAuthorisation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="amfLogin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amfPassword" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amfEndpoint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestCase", propOrder = {
    "testStep",
    "loadTest",
    "setupScript",
    "tearDownScript",
    "properties",
    "requirements",
    "reportTemplates",
    "reportScript",
    "reportParameters",
    "securityTest",
    "breakPoints"
})
public class TestCase
    extends ModelItem
{

    protected List<TestStep> testStep;
    protected List<LoadTest> loadTest;
    protected Script setupScript;
    protected Script tearDownScript;
    protected PropertiesType properties;
    protected RequirementsType requirements;
    protected List<ReportTemplate> reportTemplates;
    protected Script reportScript;
    protected PropertiesType reportParameters;
    protected List<SecurityTest> securityTest;
    protected List<BreakPoint> breakPoints;
    @XmlAttribute(name = "keepSession")
    protected Boolean keepSession;
    @XmlAttribute(name = "failOnError")
    protected Boolean failOnError;
    @XmlAttribute(name = "failTestCaseOnErrors")
    protected Boolean failTestCaseOnErrors;
    @XmlAttribute(name = "discardOkResults")
    protected Boolean discardOkResults;
    @XmlAttribute(name = "searchProperties")
    protected Boolean searchProperties;
    @XmlAttribute(name = "disabled")
    protected Boolean disabled;
    @XmlAttribute(name = "timeout")
    protected Long timeout;
    @XmlAttribute(name = "maxResults")
    protected Integer maxResults;
    @XmlAttribute(name = "wsrmEnabled")
    protected Boolean wsrmEnabled;
    @XmlAttribute(name = "wsrmVersion")
    protected String wsrmVersion;
    @XmlAttribute(name = "wsrmAckTo")
    protected String wsrmAckTo;
    @XmlAttribute(name = "wsrmExpires")
    protected Long wsrmExpires;
    @XmlAttribute(name = "amfAuthorisation")
    protected Boolean amfAuthorisation;
    @XmlAttribute(name = "amfLogin")
    protected String amfLogin;
    @XmlAttribute(name = "amfPassword")
    protected String amfPassword;
    @XmlAttribute(name = "amfEndpoint")
    protected String amfEndpoint;

    /**
     * Gets the value of the testStep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testStep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestStep }
     * 
     * 
     */
    public List<TestStep> getTestStep() {
        if (testStep == null) {
            testStep = new ArrayList<TestStep>();
        }
        return this.testStep;
    }

    /**
     * Gets the value of the loadTest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loadTest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoadTest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoadTest }
     * 
     * 
     */
    public List<LoadTest> getLoadTest() {
        if (loadTest == null) {
            loadTest = new ArrayList<LoadTest>();
        }
        return this.loadTest;
    }

    /**
     * Gets the value of the setupScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getSetupScript() {
        return setupScript;
    }

    /**
     * Sets the value of the setupScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setSetupScript(Script value) {
        this.setupScript = value;
    }

    /**
     * Gets the value of the tearDownScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getTearDownScript() {
        return tearDownScript;
    }

    /**
     * Sets the value of the tearDownScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setTearDownScript(Script value) {
        this.tearDownScript = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link RequirementsType }
     *     
     */
    public RequirementsType getRequirements() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequirementsType }
     *     
     */
    public void setRequirements(RequirementsType value) {
        this.requirements = value;
    }

    /**
     * Gets the value of the reportTemplates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportTemplates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportTemplates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportTemplate }
     * 
     * 
     */
    public List<ReportTemplate> getReportTemplates() {
        if (reportTemplates == null) {
            reportTemplates = new ArrayList<ReportTemplate>();
        }
        return this.reportTemplates;
    }

    /**
     * Gets the value of the reportScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getReportScript() {
        return reportScript;
    }

    /**
     * Sets the value of the reportScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setReportScript(Script value) {
        this.reportScript = value;
    }

    /**
     * Gets the value of the reportParameters property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getReportParameters() {
        return reportParameters;
    }

    /**
     * Sets the value of the reportParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setReportParameters(PropertiesType value) {
        this.reportParameters = value;
    }

    /**
     * Gets the value of the securityTest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityTest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityTest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityTest }
     * 
     * 
     */
    public List<SecurityTest> getSecurityTest() {
        if (securityTest == null) {
            securityTest = new ArrayList<SecurityTest>();
        }
        return this.securityTest;
    }

    /**
     * Gets the value of the breakPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the breakPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBreakPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BreakPoint }
     * 
     * 
     */
    public List<BreakPoint> getBreakPoints() {
        if (breakPoints == null) {
            breakPoints = new ArrayList<BreakPoint>();
        }
        return this.breakPoints;
    }

    /**
     * Gets the value of the keepSession property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeepSession() {
        return keepSession;
    }

    /**
     * Sets the value of the keepSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepSession(Boolean value) {
        this.keepSession = value;
    }

    /**
     * Gets the value of the failOnError property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailOnError() {
        return failOnError;
    }

    /**
     * Sets the value of the failOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailOnError(Boolean value) {
        this.failOnError = value;
    }

    /**
     * Gets the value of the failTestCaseOnErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailTestCaseOnErrors() {
        return failTestCaseOnErrors;
    }

    /**
     * Sets the value of the failTestCaseOnErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailTestCaseOnErrors(Boolean value) {
        this.failTestCaseOnErrors = value;
    }

    /**
     * Gets the value of the discardOkResults property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiscardOkResults() {
        return discardOkResults;
    }

    /**
     * Sets the value of the discardOkResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiscardOkResults(Boolean value) {
        this.discardOkResults = value;
    }

    /**
     * Gets the value of the searchProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchProperties() {
        return searchProperties;
    }

    /**
     * Sets the value of the searchProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchProperties(Boolean value) {
        this.searchProperties = value;
    }

    /**
     * Gets the value of the disabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisabled() {
        return disabled;
    }

    /**
     * Sets the value of the disabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisabled(Boolean value) {
        this.disabled = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeout(Long value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the maxResults property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxResults() {
        return maxResults;
    }

    /**
     * Sets the value of the maxResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxResults(Integer value) {
        this.maxResults = value;
    }

    /**
     * Gets the value of the wsrmEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWsrmEnabled() {
        return wsrmEnabled;
    }

    /**
     * Sets the value of the wsrmEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWsrmEnabled(Boolean value) {
        this.wsrmEnabled = value;
    }

    /**
     * Gets the value of the wsrmVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsrmVersion() {
        return wsrmVersion;
    }

    /**
     * Sets the value of the wsrmVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsrmVersion(String value) {
        this.wsrmVersion = value;
    }

    /**
     * Gets the value of the wsrmAckTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsrmAckTo() {
        return wsrmAckTo;
    }

    /**
     * Sets the value of the wsrmAckTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsrmAckTo(String value) {
        this.wsrmAckTo = value;
    }

    /**
     * Gets the value of the wsrmExpires property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWsrmExpires() {
        return wsrmExpires;
    }

    /**
     * Sets the value of the wsrmExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWsrmExpires(Long value) {
        this.wsrmExpires = value;
    }

    /**
     * Gets the value of the amfAuthorisation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAmfAuthorisation() {
        return amfAuthorisation;
    }

    /**
     * Sets the value of the amfAuthorisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAmfAuthorisation(Boolean value) {
        this.amfAuthorisation = value;
    }

    /**
     * Gets the value of the amfLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmfLogin() {
        return amfLogin;
    }

    /**
     * Sets the value of the amfLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmfLogin(String value) {
        this.amfLogin = value;
    }

    /**
     * Gets the value of the amfPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmfPassword() {
        return amfPassword;
    }

    /**
     * Sets the value of the amfPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmfPassword(String value) {
        this.amfPassword = value;
    }

    /**
     * Gets the value of the amfEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmfEndpoint() {
        return amfEndpoint;
    }

    /**
     * Sets the value of the amfEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmfEndpoint(String value) {
        this.amfEndpoint = value;
    }

}
