//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestSuite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestSuite">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="runType" type="{http://eviware.com/soapui/config}TestSuiteRunTypes" minOccurs="0"/>
 *         &lt;element name="testCase" type="{http://eviware.com/soapui/config}TestCase" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *         &lt;element name="setupScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="tearDownScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="reportScript" type="{http://eviware.com/soapui/config}Script" minOccurs="0"/>
 *         &lt;element name="reportTemplates" type="{http://eviware.com/soapui/config}ReportTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reportParameters" type="{http://eviware.com/soapui/config}PropertiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="disabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="abortOnError" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="failOnErrors" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestSuite", propOrder = {
    "runType",
    "testCase",
    "properties",
    "setupScript",
    "tearDownScript",
    "reportScript",
    "reportTemplates",
    "reportParameters"
})
public class TestSuite
    extends ModelItem
{

    protected TestSuiteRunTypes runType;
    protected List<TestCase> testCase;
    protected PropertiesType properties;
    protected Script setupScript;
    protected Script tearDownScript;
    protected Script reportScript;
    protected List<ReportTemplate> reportTemplates;
    protected PropertiesType reportParameters;
    @XmlAttribute(name = "disabled")
    protected Boolean disabled;
    @XmlAttribute(name = "abortOnError")
    protected Boolean abortOnError;
    @XmlAttribute(name = "failOnErrors")
    protected Boolean failOnErrors;
    @XmlAttribute(name = "timeout")
    protected Long timeout;

    /**
     * Gets the value of the runType property.
     * 
     * @return
     *     possible object is
     *     {@link TestSuiteRunTypes }
     *     
     */
    public TestSuiteRunTypes getRunType() {
        return runType;
    }

    /**
     * Sets the value of the runType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestSuiteRunTypes }
     *     
     */
    public void setRunType(TestSuiteRunTypes value) {
        this.runType = value;
    }

    /**
     * Gets the value of the testCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestCase }
     * 
     * 
     */
    public List<TestCase> getTestCase() {
        if (testCase == null) {
            testCase = new ArrayList<TestCase>();
        }
        return this.testCase;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the setupScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getSetupScript() {
        return setupScript;
    }

    /**
     * Sets the value of the setupScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setSetupScript(Script value) {
        this.setupScript = value;
    }

    /**
     * Gets the value of the tearDownScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getTearDownScript() {
        return tearDownScript;
    }

    /**
     * Sets the value of the tearDownScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setTearDownScript(Script value) {
        this.tearDownScript = value;
    }

    /**
     * Gets the value of the reportScript property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getReportScript() {
        return reportScript;
    }

    /**
     * Sets the value of the reportScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setReportScript(Script value) {
        this.reportScript = value;
    }

    /**
     * Gets the value of the reportTemplates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportTemplates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportTemplates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportTemplate }
     * 
     * 
     */
    public List<ReportTemplate> getReportTemplates() {
        if (reportTemplates == null) {
            reportTemplates = new ArrayList<ReportTemplate>();
        }
        return this.reportTemplates;
    }

    /**
     * Gets the value of the reportParameters property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getReportParameters() {
        return reportParameters;
    }

    /**
     * Sets the value of the reportParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setReportParameters(PropertiesType value) {
        this.reportParameters = value;
    }

    /**
     * Gets the value of the disabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisabled() {
        return disabled;
    }

    /**
     * Sets the value of the disabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisabled(Boolean value) {
        this.disabled = value;
    }

    /**
     * Gets the value of the abortOnError property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbortOnError() {
        return abortOnError;
    }

    /**
     * Sets the value of the abortOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbortOnError(Boolean value) {
        this.abortOnError = value;
    }

    /**
     * Gets the value of the failOnErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailOnErrors() {
        return failOnErrors;
    }

    /**
     * Sets the value of the failOnErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailOnErrors(Boolean value) {
        this.failOnErrors = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeout(Long value) {
        this.timeout = value;
    }

}
