//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestOnDemandKeystore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestOnDemandKeystore">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="File" type="{http://eviware.com/soapui/config}TestOnDemandFile"/>
 *         &lt;element name="Password" type="{http://eviware.com/soapui/config}TestOnDemandKeystorePassword"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestOnDemandKeystore", propOrder = {
    "file",
    "password"
})
public class TestOnDemandKeystore {

    @XmlElement(name = "File", required = true)
    protected TestOnDemandFile file;
    @XmlElement(name = "Password", required = true)
    protected TestOnDemandKeystorePassword password;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link TestOnDemandFile }
     *     
     */
    public TestOnDemandFile getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestOnDemandFile }
     *     
     */
    public void setFile(TestOnDemandFile value) {
        this.file = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link TestOnDemandKeystorePassword }
     *     
     */
    public TestOnDemandKeystorePassword getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestOnDemandKeystorePassword }
     *     
     */
    public void setPassword(TestOnDemandKeystorePassword value) {
        this.password = value;
    }

}
