//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Workspace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Workspace">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}ModelItem">
 *       &lt;sequence>
 *         &lt;element name="project" type="{http://eviware.com/soapui/config}WorkspaceProject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="soapui-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="projectRoot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Workspace", propOrder = {
    "project"
})
public class Workspace
    extends ModelItem
{

    protected List<WorkspaceProject> project;
    @XmlAttribute(name = "soapui-version")
    protected String soapuiVersion;
    @XmlAttribute(name = "projectRoot")
    protected String projectRoot;

    /**
     * Gets the value of the project property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the project property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkspaceProject }
     * 
     * 
     */
    public List<WorkspaceProject> getProject() {
        if (project == null) {
            project = new ArrayList<WorkspaceProject>();
        }
        return this.project;
    }

    /**
     * Gets the value of the soapuiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoapuiVersion() {
        return soapuiVersion;
    }

    /**
     * Sets the value of the soapuiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoapuiVersion(String value) {
        this.soapuiVersion = value;
    }

    /**
     * Gets the value of the projectRoot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectRoot() {
        return projectRoot;
    }

    /**
     * Sets the value of the projectRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectRoot(String value) {
        this.projectRoot = value;
    }

}
