//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WsaConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WsaConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="replyTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="faultTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="messageID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relationshipType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relatesTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://eviware.com/soapui/config}WsaVersionType" />
 *       &lt;attribute name="mustUnderstand" type="{http://eviware.com/soapui/config}MustUnderstandType" />
 *       &lt;attribute name="generateMessageId" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="addDefaultTo" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="addDefaultAction" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="replyToRefParams" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="faultToRefParams" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WsaConfig")
public class WsaConfig {

    @XmlAttribute(name = "replyTo")
    protected String replyTo;
    @XmlAttribute(name = "faultTo")
    protected String faultTo;
    @XmlAttribute(name = "action")
    protected String action;
    @XmlAttribute(name = "from")
    protected String from;
    @XmlAttribute(name = "messageID")
    protected String messageID;
    @XmlAttribute(name = "to")
    protected String to;
    @XmlAttribute(name = "relationshipType")
    protected String relationshipType;
    @XmlAttribute(name = "relatesTo")
    protected String relatesTo;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "mustUnderstand")
    protected MustUnderstandType mustUnderstand;
    @XmlAttribute(name = "generateMessageId")
    protected Boolean generateMessageId;
    @XmlAttribute(name = "addDefaultTo")
    protected Boolean addDefaultTo;
    @XmlAttribute(name = "addDefaultAction")
    protected Boolean addDefaultAction;
    @XmlAttribute(name = "replyToRefParams")
    protected String replyToRefParams;
    @XmlAttribute(name = "faultToRefParams")
    protected String faultToRefParams;

    /**
     * Gets the value of the replyTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyTo() {
        return replyTo;
    }

    /**
     * Sets the value of the replyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyTo(String value) {
        this.replyTo = value;
    }

    /**
     * Gets the value of the faultTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultTo() {
        return faultTo;
    }

    /**
     * Sets the value of the faultTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultTo(String value) {
        this.faultTo = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the relationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipType() {
        return relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipType(String value) {
        this.relationshipType = value;
    }

    /**
     * Gets the value of the relatesTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatesTo() {
        return relatesTo;
    }

    /**
     * Sets the value of the relatesTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatesTo(String value) {
        this.relatesTo = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the mustUnderstand property.
     * 
     * @return
     *     possible object is
     *     {@link MustUnderstandType }
     *     
     */
    public MustUnderstandType getMustUnderstand() {
        return mustUnderstand;
    }

    /**
     * Sets the value of the mustUnderstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link MustUnderstandType }
     *     
     */
    public void setMustUnderstand(MustUnderstandType value) {
        this.mustUnderstand = value;
    }

    /**
     * Gets the value of the generateMessageId property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGenerateMessageId() {
        return generateMessageId;
    }

    /**
     * Sets the value of the generateMessageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGenerateMessageId(Boolean value) {
        this.generateMessageId = value;
    }

    /**
     * Gets the value of the addDefaultTo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddDefaultTo() {
        return addDefaultTo;
    }

    /**
     * Sets the value of the addDefaultTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddDefaultTo(Boolean value) {
        this.addDefaultTo = value;
    }

    /**
     * Gets the value of the addDefaultAction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddDefaultAction() {
        return addDefaultAction;
    }

    /**
     * Sets the value of the addDefaultAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddDefaultAction(Boolean value) {
        this.addDefaultAction = value;
    }

    /**
     * Gets the value of the replyToRefParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyToRefParams() {
        return replyToRefParams;
    }

    /**
     * Sets the value of the replyToRefParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyToRefParams(String value) {
        this.replyToRefParams = value;
    }

    /**
     * Gets the value of the faultToRefParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultToRefParams() {
        return faultToRefParams;
    }

    /**
     * Sets the value of the faultToRefParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultToRefParams(String value) {
        this.faultToRefParams = value;
    }

}
