//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WsdlInterface complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WsdlInterface">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}Interface">
 *       &lt;sequence>
 *         &lt;element name="operation" type="{http://eviware.com/soapui/config}Operation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="definition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bindingName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="soapVersion" type="{http://eviware.com/soapui/config}SoapVersionTypes" />
 *       &lt;attribute name="wsaVersion" type="{http://eviware.com/soapui/config}WsaVersionType" />
 *       &lt;attribute name="anonymous" type="{http://eviware.com/soapui/config}AnonymousType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WsdlInterface", propOrder = {
    "operation"
})
public class WsdlInterface
    extends Interface
{

    protected List<Operation> operation;
    @XmlAttribute(name = "definition")
    protected String definition;
    @XmlAttribute(name = "bindingName")
    protected String bindingName;
    @XmlAttribute(name = "soapVersion")
    protected String soapVersion;
    @XmlAttribute(name = "wsaVersion")
    protected String wsaVersion;
    @XmlAttribute(name = "anonymous")
    protected AnonymousType anonymous;

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Operation }
     * 
     * 
     */
    public List<Operation> getOperation() {
        if (operation == null) {
            operation = new ArrayList<Operation>();
        }
        return this.operation;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    /**
     * Gets the value of the bindingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindingName() {
        return bindingName;
    }

    /**
     * Sets the value of the bindingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindingName(String value) {
        this.bindingName = value;
    }

    /**
     * Gets the value of the soapVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoapVersion() {
        return soapVersion;
    }

    /**
     * Sets the value of the soapVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoapVersion(String value) {
        this.soapVersion = value;
    }

    /**
     * Gets the value of the wsaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsaVersion() {
        return wsaVersion;
    }

    /**
     * Sets the value of the wsaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsaVersion(String value) {
        this.wsaVersion = value;
    }

    /**
     * Gets the value of the anonymous property.
     * 
     * @return
     *     possible object is
     *     {@link AnonymousType }
     *     
     */
    public AnonymousType getAnonymous() {
        return anonymous;
    }

    /**
     * Sets the value of the anonymous property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnonymousType }
     *     
     */
    public void setAnonymous(AnonymousType value) {
        this.anonymous = value;
    }

}
