//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSSAddUsernameEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSSAddUsernameEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eviware.com/soapui/config}WSSEntry">
 *       &lt;attribute name="addCreated" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="addNonce" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="passwordType" type="{http://eviware.com/soapui/config}WSSUsernamePasswordPasswordType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSSAddUsernameEntry")
public class WSSAddUsernameEntry
    extends WSSEntry
{

    @XmlAttribute(name = "addCreated")
    protected Boolean addCreated;
    @XmlAttribute(name = "addNonce")
    protected Boolean addNonce;
    @XmlAttribute(name = "passwordType")
    protected WSSUsernamePasswordPasswordType passwordType;

    /**
     * Gets the value of the addCreated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddCreated() {
        return addCreated;
    }

    /**
     * Sets the value of the addCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddCreated(Boolean value) {
        this.addCreated = value;
    }

    /**
     * Gets the value of the addNonce property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddNonce() {
        return addNonce;
    }

    /**
     * Sets the value of the addNonce property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddNonce(Boolean value) {
        this.addNonce = value;
    }

    /**
     * Gets the value of the passwordType property.
     * 
     * @return
     *     possible object is
     *     {@link WSSUsernamePasswordPasswordType }
     *     
     */
    public WSSUsernamePasswordPasswordType getPasswordType() {
        return passwordType;
    }

    /**
     * Sets the value of the passwordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSSUsernamePasswordPasswordType }
     *     
     */
    public void setPasswordType(WSSUsernamePasswordPasswordType value) {
        this.passwordType = value;
    }

}
