//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.27 at 05:36:21 PM CEST 
//


package org.aleroddepaz.soapuimodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlBombSecurityCheck complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlBombSecurityCheck">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xmlBombs" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="attachXmlBomb" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="xmlAttachmentPrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlBombSecurityCheck", propOrder = {
    "xmlBombs"
})
public class XmlBombSecurityCheck {

    protected List<String> xmlBombs;
    @XmlAttribute(name = "attachXmlBomb")
    protected Boolean attachXmlBomb;
    @XmlAttribute(name = "xmlAttachmentPrefix")
    protected String xmlAttachmentPrefix;

    /**
     * Gets the value of the xmlBombs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xmlBombs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXmlBombs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getXmlBombs() {
        if (xmlBombs == null) {
            xmlBombs = new ArrayList<String>();
        }
        return this.xmlBombs;
    }

    /**
     * Gets the value of the attachXmlBomb property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAttachXmlBomb() {
        return attachXmlBomb;
    }

    /**
     * Sets the value of the attachXmlBomb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAttachXmlBomb(Boolean value) {
        this.attachXmlBomb = value;
    }

    /**
     * Gets the value of the xmlAttachmentPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlAttachmentPrefix() {
        return xmlAttachmentPrefix;
    }

    /**
     * Sets the value of the xmlAttachmentPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlAttachmentPrefix(String value) {
        this.xmlAttachmentPrefix = value;
    }

}
